# Generated by Django 3.1.6 on 2021-02-20 09:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_insta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insta',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='insta',
            name='image',
            field=models.FileField(default='', upload_to='accounts/images'),
        ),
    ]
